ignore:
- '**/target/**'
- '**/__pycache__'
- '**/*.pyc'
- .git/**
- .github/**
- .pytest_cache/**
- '*.egg-info/**'
- __init__.py
- '*__init__.py'
main_service: python
services:
  python:
    environment:
    - RUSTUP_HOME=/usr/local/rustup
    - CARGO_HOME=/usr/local/cargo
    - PATH=/usr/local/cargo/bin:$PATH
    image: python:3.11
setup_commands:
- apt-get update && apt-get install -y curl build-essential pkg-config
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile
  minimal
- source $CARGO_HOME/env
- python -m pip install --upgrade pip
- pip install setuptools wheel setuptools-rust>=1.5.2
- pip install pytest hypothesis coverage pytest-json-report
- pip install -e .
single_file_test_commands:
- coverage run -m pytest "$TEST_FILE" --import-mode=append --json-report
- coverage json
test_commands:
- coverage run -m pytest tests --import-mode=append --show-capture=no --json-report
- coverage combine || true
- coverage json -i || true
