/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tiktoken_Encoding */

#ifndef _Included_tiktoken_Encoding
#define _Included_tiktoken_Encoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tiktoken_Encoding
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tiktoken_Encoding_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tiktoken_Encoding
 * Method:    encode
 * Signature: (Ljava/lang/String;[Ljava/lang/String;J)[J
 */
JNIEXPORT jlongArray JNICALL Java_tiktoken_Encoding_encode
  (JNIEnv *, jobject, jstring, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
