// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

::uniffi::setup_scaffolding!("tiktoken");

// Export info about this UDL file
// See `uniffi_bindgen::macro_metadata` for how this is used.

const UNIFFI_META_CONST_UDL_TIKTOKEN: ::uniffi::MetadataBuffer =
    ::uniffi::MetadataBuffer::from_code(::uniffi::metadata::codes::UDL_FILE)
        .concat_str("tiktoken")
        .concat_str("tiktoken")
        .concat_str("tiktoken");

#[doc(hidden)]
#[unsafe(no_mangle)]
pub static UNIFFI_META_UDL_TIKTOKEN: [u8; UNIFFI_META_CONST_UDL_TIKTOKEN.size] =
    UNIFFI_META_CONST_UDL_TIKTOKEN.into_array();

uniffi::deps::static_assertions::assert_impl_all!(::std::string::String: ::std::cmp::Eq, ::std::hash::Hash); // record<::std::string::String, u32>

// Error definitions, corresponding to `error` in the UDL.

#[::uniffi::udl_derive(Error)]
#[uniffi(flat_error)]

enum r#TiktokenError {
    r#ValueError {},
    r#KeyError {},
    r#DecodeError {},
}

// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.

#[::uniffi::udl_derive(Record)]
struct r#EncodingResult {
    r#tokens: std::vec::Vec<u32>,
    r#last_piece_token_len: u64,
}

#[::uniffi::udl_derive(Record)]
struct r#UnstableEncodingResult {
    r#tokens: std::vec::Vec<u32>,
    r#completions: std::vec::Vec<std::vec::Vec<u32>>,
}

// Top level functions, corresponding to UDL `namespace` functions.

#[::uniffi::export_for_udl]
pub fn r#new_core_bpe(
    r#encoder: ::std::collections::HashMap<::std::string::String, u32>,
    r#special_tokens_encoder: ::std::collections::HashMap<::std::string::String, u32>,
    r#pattern: ::std::string::String,
) -> ::std::result::Result<::std::sync::Arc<r#CoreBPE>, r#TiktokenError> {
    unreachable!()
}

// Object definitions, corresponding to UDL `interface` definitions.

#[::uniffi::udl_derive(Object)]
struct r#CoreBPE {}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    #[uniffi::constructor]
    pub fn r#new(
        r#encoder: ::std::collections::HashMap<::std::string::String, u32>,
        r#special_tokens_encoder: ::std::collections::HashMap<::std::string::String, u32>,
        r#pattern: ::std::string::String,
    ) -> ::std::sync::Arc<r#CoreBPE> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#decode_bytes(
        &self,
        r#tokens: std::vec::Vec<u32>,
    ) -> ::std::result::Result<::std::vec::Vec<u8>, r#TiktokenError> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#decode_single_token_bytes(
        &self,
        r#token: u32,
    ) -> ::std::result::Result<::std::vec::Vec<u8>, r#TiktokenError> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode(
        &self,
        r#text: ::std::string::String,
        r#allowed_special: std::vec::Vec<::std::string::String>,
    ) -> std::vec::Vec<u32> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_bytes(&self, r#input: ::std::vec::Vec<u8>) -> std::vec::Vec<u32> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_ordinary(&self, r#text: ::std::string::String) -> std::vec::Vec<u32> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_single_piece(&self, r#piece: ::std::vec::Vec<u8>) -> std::vec::Vec<u32> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_single_token(
        &self,
        r#piece: ::std::vec::Vec<u8>,
    ) -> ::std::result::Result<u32, r#TiktokenError> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_with_details(
        &self,
        r#text: ::std::string::String,
        r#allowed_special: std::vec::Vec<::std::string::String>,
    ) -> r#EncodingResult {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_with_special_tokens(
        &self,
        r#text: ::std::string::String,
    ) -> std::vec::Vec<u32> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#encode_with_unstable(
        &self,
        r#text: ::std::string::String,
        r#allowed_special: std::vec::Vec<::std::string::String>,
    ) -> r#UnstableEncodingResult {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#max_token_value(&self) -> u32 {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#n_vocab(&self) -> u32 {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#special_tokens(&self) -> std::vec::Vec<::std::string::String> {
        unreachable!()
    }
}
#[::uniffi::export_for_udl]
impl r#CoreBPE {
    pub fn r#token_byte_values(&self) -> std::vec::Vec<::std::vec::Vec<u8>> {
        unreachable!()
    }
}

// Callback Interface definitions, corresponding to UDL `callback interface` definitions.

// Export scaffolding checksums for UDL items

#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_func_new_core_bpe() -> u16 {
    56117
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_decode_bytes() -> u16 {
    55010
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_decode_single_token_bytes() -> u16 {
    5116
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode() -> u16 {
    29815
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_bytes() -> u16 {
    62700
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_ordinary() -> u16 {
    27373
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_single_piece() -> u16 {
    59626
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_single_token() -> u16 {
    44485
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_with_details() -> u16 {
    44545
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_with_special_tokens() -> u16 {
    3792
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_encode_with_unstable() -> u16 {
    58939
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_max_token_value() -> u16 {
    1036
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_n_vocab() -> u16 {
    6443
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_special_tokens() -> u16 {
    37553
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_method_corebpe_token_byte_values() -> u16 {
    22300
}
#[unsafe(no_mangle)]
#[doc(hidden)]
pub extern "C" fn r#uniffi_tiktoken_checksum_constructor_corebpe_new() -> u16 {
    33616
}
